version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "587:587"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: QWERTY
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"